[package]
name = "gcm-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
confy = "0.5.1"
reqwest = { version = "0.11.14", features = ["json"] }
rpassword = "7.2.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"

# Just for the testing
tokio = { version = "1.25.0", features = ["full"] }
