[package]
name = "gcm-ai"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"
codegen-units = 1
strip = true

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
confy = "0.5.1"
once_cell = "1.17.1"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
reqwest = { version = "0.11.14", features = ["json"] }
rpassword = "7.2.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["macros", "rt", "process"] }
